# Generated by Django 5.2.8 on 2025-12-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
